force-app/main/default/objects/Tickets__c/Tickets__c.object-meta.xml
<CustomObject>
    <label>Tickets</label>
    <nameField>
        <label>Tickets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tickets__c/fields/descripcion_incidencia__c.field-meta.xml
<CustomField>
    <fullName>descripcion_incidencia__c</fullName>
    <description>se describe la incidencia</description>
    <label>descripcion_incidencia</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tickets__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <description>permite agregar si es necesariio</description>
    <label>ImagenURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Tickets__c/fields/imagenagregada__c.field-meta.xml
<CustomField>
    <fullName>imagenagregada__c</fullName>
    <description>agrega una imagen de ser necesario</description>
    <formula>IMAGE(Image_URL__c,&quot;imagen incidencia&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>imagen agregada</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tickets__c/fields/Reinicidencia__c.field-meta.xml
<CustomField>
    <fullName>Reinicidencia__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reinicidencia</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tickets__c/fields/Tipo_Incidencia__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Incidencia__c</fullName>
    <label>TipoIncidencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CAIDA DE INTERNET</fullName>
                <default>true</default>
                <label>CAIDA DE INTERNET</label>
            </value>
            <value>
                <fullName>FALLA DE LUZ</fullName>
            </value>
            <value>
                <fullName>SIN FICHAS</fullName>
            </value>
            <value>
                <fullName>VULNERACIONES,</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ticketService.cls
public with sharing class ticketService {
     @AuraEnabled(cacheable=true)
    public static List<Tickets__c> getallTickets() {
        return [
            SELECT Id,  descripcion_incidencia__c,Image_URL__c, imagenagregada__c,Tipo_Incidencia__c,Reinicidencia__c
         FROM Tickets__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Tickets__c> getTicketsByDescription(String description) {
        string searchTerm = '%' + description + '%';//evita la inyeccion de SQL y permite buscar coincidencias parciales
        return [
            SELECT Id, descripcion_incidencia__c, Image_URL__c, imagenagregada__c, Tipo_Incidencia__c, Reinicidencia__c
            FROM Tickets__c
            WHERE descripcion_incidencia__c LIKE :searchTerm
        ];
    }
}