force-app/main/default/objects/ticketsplatform__e/ticketsplatform__e.object-meta.xml
<CustomObject>
    <label>ticketsplatform</label>
    <pluralLabel>ticketsplatform</pluralLabel>
</CustomObject>

force-app/main/default/objects/ticketsplatform__e/fields/ticket_id__c.field-meta.xml
<CustomField>
    <fullName>ticket_id__c</fullName>
    <label>ticket_id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ticketsplatform__e/fields/TipoIncidenciaplat__c.field-meta.xml
<CustomField>
    <fullName>TipoIncidenciaplat__c</fullName>
    <label>TipoIncidenciaPlat</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EjecutarPlattformEvent.cls
public with sharing class EjecutarPlattformEvent {
  public static void EjecutarrPlattformEvent() {
    System.debug('Ejecutando el evento de prueba en Salesforce');
    ticketsplatform__e ptfEvent = new ticketsplatform__e(
      ticket_id__c = 'Evento de prueba',
      TipoIncidenciaplat__c = 'Este es un evento de prueba para ejecutar una acción en Salesforce'
    );
    list<ticketsplatform__e> ptfEventTickes = new List<ticketsplatform__e>();
    ptfEventTickes.add(ptfEvent);
    System.debug('Publicado el evento de prueba en Salesforce');

    Database.SaveResult[] results = EventBus.publish(ptfEventTickes);
    for (Database.SaveResult result : results) {
      if (result.isSuccess()) {
        System.debug(
          'Evento publicado con éxito. ID del evento: ' + result.getId()
        );
      } else {
        System.debug(
          'Error al publicar el evento: ' + result.getErrors()[0].getMessage()
        );
      }
    }
  }
}